import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Customers from '@/shared/Customers/Customers'
import customers from '../../../db.json'
import { createServer } from "miragejs"
import Index from '@/shared/Index'

createServer({
  routes() {
    this.get("/api/movies", () => ({
      movies: [
        { id: 1, name: "Inception", year: 2010 },
        { id: 2, name: "Interstellar", year: 2014 },
        { id: 3, name: "Dunkirk", year: 2017 },
      ],
    }))
    this.get("/api/customers", () => (customers))
  },
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Customers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <Index />
        <Customers />
      </div>
    </>
  )
}
